/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    characters: Character;
    categories: Category;
    submissions: Submission;
    works: Work;
    topics: Topic;
    'takedown-requests': TakedownRequest;
    'publish-runs': PublishRun;
    'audit-events': AuditEvent;
    'legacy-snapshots': LegacySnapshot;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    characters: CharactersSelect<false> | CharactersSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    submissions: SubmissionsSelect<false> | SubmissionsSelect<true>;
    works: WorksSelect<false> | WorksSelect<true>;
    topics: TopicsSelect<false> | TopicsSelect<true>;
    'takedown-requests': TakedownRequestsSelect<false> | TakedownRequestsSelect<true>;
    'publish-runs': PublishRunsSelect<false> | PublishRunsSelect<true>;
    'audit-events': AuditEventsSelect<false> | AuditEventsSelect<true>;
    'legacy-snapshots': LegacySnapshotsSelect<false> | LegacySnapshotsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * 机器人只能使用 API Key，不能登录后台界面。
   */
  role: 'owner' | 'bot';
  /**
   * 审计记录中的操作者名称。
   */
  displayName?: string | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  hasAPIKey?: boolean | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  sha256?: string | null;
  mediaRole: 'preview' | 'attachment';
  storageKind: 'payload-private' | 'content-repository' | 'external';
  externalUrl?: string | null;
  sourcePath?: string | null;
  isAnimated?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "characters".
 */
export interface Character {
  id: number;
  characterId: string;
  name: string;
  aliases?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  status: 'active' | 'inactive';
  inSubmissionForm?: boolean | null;
  legacyOrder?: number | null;
  legacyData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  categoryId: string;
  name: string;
  description?: string | null;
  status: 'active' | 'inactive';
  legacyOrder?: number | null;
  legacyData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions".
 */
export interface Submission {
  id: number;
  title: string;
  submissionId: string;
  source: 'web' | 'github-issue' | 'qq' | 'manual';
  sourceIds?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  sha256?: string | null;
  media?: (number | null) | Media;
  fields?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  review?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  state:
    | 'received'
    | 'reviewing'
    | 'auto_passed'
    | 'auto_rejected'
    | 'needs_manual'
    | 'approved'
    | 'rejected'
    | 'ready_to_publish'
    | 'publishing'
    | 'published'
    | 'publish_failed';
  stateHistory?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  origin?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  work?: (number | null) | Work;
  syncedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works".
 */
export interface Work {
  id: number;
  workId: string;
  /**
   * 新作品发布前可为空，由发布器生成后回写。
   */
  slug?: string | null;
  name: string;
  description?: string | null;
  commentary?: string | null;
  kind: 'submission' | 'owner-picks' | 'blue-fish';
  channel: 'web' | 'github-issue' | 'qq' | 'manual' | 'owner' | 'blue-fish';
  submissionId?: string | null;
  sha256?: string | null;
  character: number | Character;
  categories?: (number | Category)[] | null;
  tags?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  preview?: (number | null) | Media;
  legacyPaths?: {
    path?: string | null;
    thumbnailPath?: string | null;
    fullPath?: string | null;
    externalOriginalUrl?: string | null;
  };
  format?: string | null;
  mimeType?: string | null;
  isAnimated?: boolean | null;
  width?: number | null;
  height?: number | null;
  fileSize?: number | null;
  submitter?: {
    credit?: ('anonymous' | 'named') | null;
    name?: string | null;
    url?: string | null;
    github?: string | null;
  };
  origin?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  license?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status: 'pending' | 'published' | 'hidden' | 'removed' | 'deleted';
  needsPublish?: boolean | null;
  changeAction?: ('add' | 'update' | 'hide' | 'restore' | 'remove' | 'delete') | null;
  publishedAt?: string | null;
  lastPublishedAt?: string | null;
  lastPublishRun?: (number | null) | PublishRun;
  review?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  legacySource?: string | null;
  legacyOrder?: number | null;
  legacyData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publish-runs".
 */
export interface PublishRun {
  id: number;
  runId: string;
  trigger: 'manual' | 'bot';
  mode: 'preview' | 'publish' | 'rollback';
  status: 'queued' | 'in_progress' | 'succeeded' | 'failed' | 'cancelled';
  requestedAt?: string | null;
  requestedBy?: (number | null) | User;
  works?: (number | Work)[] | null;
  plannedChanges?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  summary?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  step?: string | null;
  commits?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  releasePath?: string | null;
  healthCheck?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  results?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  log?: string | null;
  error?: string | null;
  startedAt?: string | null;
  finishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics".
 */
export interface Topic {
  id: number;
  topicId: string;
  name: string;
  summary: string;
  nameEn?: string | null;
  summaryEn?: string | null;
  nameJa?: string | null;
  summaryJa?: string | null;
  cover?: (number | null) | Work;
  works?: (number | Work)[] | null;
  /**
   * 整组可留空；填写任意一项即视为作者型专题，此时作者名与首选渠道（渠道第一项）为必需。
   */
  author?: {
    /**
     * 作者型专题必填；可留空表示普通专题。
     */
    name?: string | null;
    /**
     * 选填，仅支持 http/https 链接。
     */
    url?: string | null;
    /**
     * 选填。
     */
    bio?: string | null;
    /**
     * 可增删、上下移动；按列表顺序展示，第一项为首选联系方式。
     */
    channels?:
      | {
          /**
           * 必填，如 Bilibili、Pixiv、微博。
           */
          platform: string;
          /**
           * 选填，留空时显示平台名。
           */
          label?: string | null;
          /**
           * 必填，仅支持 http/https 链接。
           */
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  status: 'draft' | 'active';
  order: number;
  needsPublish?: boolean | null;
  lastPublishedAt?: string | null;
  lastPublishRun?: (number | null) | PublishRun;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "takedown-requests".
 */
export interface TakedownRequest {
  id: number;
  requestId: string;
  requestType: 'takedown' | 'attribution' | 'source-correction' | 'license-correction';
  work?: (number | null) | Work;
  requester?: {
    name?: string | null;
    contact?: string | null;
    proof?: string | null;
  };
  status: 'received' | 'investigating' | 'approved' | 'rejected' | 'completed';
  decisionNote?: string | null;
  processedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-events".
 */
export interface AuditEvent {
  id: number;
  actorType: 'human' | 'ai' | 'system';
  actor?: (number | null) | User;
  /**
   * 用户显示名或邮箱；机器人记为账号名。
   */
  actorName: string;
  action: string;
  targetType: string;
  targetId: string;
  before?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  after?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  requestId?: string | null;
  ip?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legacy-snapshots".
 */
export interface LegacySnapshot {
  id: number;
  key: string;
  text: string;
  eol: 'lf' | 'crlf';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'characters';
        value: number | Character;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'submissions';
        value: number | Submission;
      } | null)
    | ({
        relationTo: 'works';
        value: number | Work;
      } | null)
    | ({
        relationTo: 'topics';
        value: number | Topic;
      } | null)
    | ({
        relationTo: 'takedown-requests';
        value: number | TakedownRequest;
      } | null)
    | ({
        relationTo: 'publish-runs';
        value: number | PublishRun;
      } | null)
    | ({
        relationTo: 'audit-events';
        value: number | AuditEvent;
      } | null)
    | ({
        relationTo: 'legacy-snapshots';
        value: number | LegacySnapshot;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  displayName?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  hasAPIKey?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  sha256?: T;
  mediaRole?: T;
  storageKind?: T;
  externalUrl?: T;
  sourcePath?: T;
  isAnimated?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "characters_select".
 */
export interface CharactersSelect<T extends boolean = true> {
  characterId?: T;
  name?: T;
  aliases?:
    | T
    | {
        value?: T;
        id?: T;
      };
  status?: T;
  inSubmissionForm?: T;
  legacyOrder?: T;
  legacyData?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  categoryId?: T;
  name?: T;
  description?: T;
  status?: T;
  legacyOrder?: T;
  legacyData?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions_select".
 */
export interface SubmissionsSelect<T extends boolean = true> {
  title?: T;
  submissionId?: T;
  source?: T;
  sourceIds?:
    | T
    | {
        value?: T;
        id?: T;
      };
  sha256?: T;
  media?: T;
  fields?: T;
  review?: T;
  state?: T;
  stateHistory?: T;
  origin?: T;
  work?: T;
  syncedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works_select".
 */
export interface WorksSelect<T extends boolean = true> {
  workId?: T;
  slug?: T;
  name?: T;
  description?: T;
  commentary?: T;
  kind?: T;
  channel?: T;
  submissionId?: T;
  sha256?: T;
  character?: T;
  categories?: T;
  tags?:
    | T
    | {
        value?: T;
        id?: T;
      };
  preview?: T;
  legacyPaths?:
    | T
    | {
        path?: T;
        thumbnailPath?: T;
        fullPath?: T;
        externalOriginalUrl?: T;
      };
  format?: T;
  mimeType?: T;
  isAnimated?: T;
  width?: T;
  height?: T;
  fileSize?: T;
  submitter?:
    | T
    | {
        credit?: T;
        name?: T;
        url?: T;
        github?: T;
      };
  origin?: T;
  license?: T;
  status?: T;
  needsPublish?: T;
  changeAction?: T;
  publishedAt?: T;
  lastPublishedAt?: T;
  lastPublishRun?: T;
  review?: T;
  legacySource?: T;
  legacyOrder?: T;
  legacyData?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics_select".
 */
export interface TopicsSelect<T extends boolean = true> {
  topicId?: T;
  name?: T;
  summary?: T;
  nameEn?: T;
  summaryEn?: T;
  nameJa?: T;
  summaryJa?: T;
  cover?: T;
  works?: T;
  author?:
    | T
    | {
        name?: T;
        url?: T;
        bio?: T;
        channels?:
          | T
          | {
              platform?: T;
              label?: T;
              url?: T;
              id?: T;
            };
      };
  status?: T;
  order?: T;
  needsPublish?: T;
  lastPublishedAt?: T;
  lastPublishRun?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "takedown-requests_select".
 */
export interface TakedownRequestsSelect<T extends boolean = true> {
  requestId?: T;
  requestType?: T;
  work?: T;
  requester?:
    | T
    | {
        name?: T;
        contact?: T;
        proof?: T;
      };
  status?: T;
  decisionNote?: T;
  processedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publish-runs_select".
 */
export interface PublishRunsSelect<T extends boolean = true> {
  runId?: T;
  trigger?: T;
  mode?: T;
  status?: T;
  requestedAt?: T;
  requestedBy?: T;
  works?: T;
  plannedChanges?: T;
  summary?: T;
  step?: T;
  commits?: T;
  releasePath?: T;
  healthCheck?: T;
  results?: T;
  log?: T;
  error?: T;
  startedAt?: T;
  finishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-events_select".
 */
export interface AuditEventsSelect<T extends boolean = true> {
  actorType?: T;
  actor?: T;
  actorName?: T;
  action?: T;
  targetType?: T;
  targetId?: T;
  before?: T;
  after?: T;
  requestId?: T;
  ip?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legacy-snapshots_select".
 */
export interface LegacySnapshotsSelect<T extends boolean = true> {
  key?: T;
  text?: T;
  eol?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}