/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    characters: Character;
    categories: Category;
    submissions: Submission;
    works: Work;
    'takedown-requests': TakedownRequest;
    'publish-runs': PublishRun;
    'audit-events': AuditEvent;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    characters: CharactersSelect<false> | CharactersSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    submissions: SubmissionsSelect<false> | SubmissionsSelect<true>;
    works: WorksSelect<false> | WorksSelect<true>;
    'takedown-requests': TakedownRequestsSelect<false> | TakedownRequestsSelect<true>;
    'publish-runs': PublishRunsSelect<false> | PublishRunsSelect<true>;
    'audit-events': AuditEventsSelect<false> | AuditEventsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * 控制后台菜单和业务操作权限；AI 服务账号不应获得登录后台的权限。
   */
  role: 'owner' | 'editor' | 'reviewer' | 'publisher' | 'ai-agent';
  displayName?: string | null;
  /**
   * 给 AI 或自动化使用的账号；后续接入 API Key 时使用。
   */
  isServiceAccount?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  sha256?: string | null;
  mediaRole: 'original' | 'large' | 'preview' | 'attachment';
  storageKind: 'payload-private' | 'content-repository' | 'external';
  externalUrl?: string | null;
  sourcePath?: string | null;
  isAnimated?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "characters".
 */
export interface Character {
  id: number;
  characterId: string;
  name: string;
  aliases?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  status: 'active' | 'inactive';
  inSubmissionForm?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  categoryId: string;
  name: string;
  description?: string | null;
  status: 'active' | 'inactive';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions".
 */
export interface Submission {
  id: number;
  title: string;
  submissionId: string;
  source: 'web' | 'github-issue' | 'qq' | 'feishu' | 'manual';
  sourceId?: string | null;
  sourceIds?:
    | {
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  asset: number | Media;
  sha256: string;
  format?: string | null;
  mime?: string | null;
  bytes?: number | null;
  fields?: {
    name?: string | null;
    characterText?: string | null;
    description?: string | null;
    tags?: string | null;
    originType?: string | null;
    originAuthor?: string | null;
    originUrl?: string | null;
    licenseType?: string | null;
    licenseNote?: string | null;
  };
  state:
    | 'received'
    | 'reviewing'
    | 'auto_passed'
    | 'auto_rejected'
    | 'needs_manual'
    | 'approved'
    | 'rejected'
    | 'ready_to_publish'
    | 'publishing'
    | 'published'
    | 'publish_failed';
  review?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  stateHistory?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  submitter?: {
    name?: string | null;
    github?: string | null;
  };
  origin?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  humanDecision?: {
    decision?: ('approved' | 'rejected') | null;
    reason?: string | null;
    actor?: string | null;
    at?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works".
 */
export interface Work {
  id: number;
  workId: string;
  slug: string;
  name: string;
  description?: string | null;
  commentary?: string | null;
  kind: 'submission' | 'owner-picks' | 'blue-fish';
  character: number | Character;
  categories?: (number | Category)[] | null;
  tags?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  original?: (number | null) | Media;
  preview?: (number | null) | Media;
  large?: (number | null) | Media;
  legacyPaths?: {
    path?: string | null;
    thumbnailPath?: string | null;
    fullPath?: string | null;
    externalOriginalUrl?: string | null;
  };
  submitter?: {
    name?: string | null;
    github?: string | null;
  };
  origin?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  license?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status: 'draft' | 'approved' | 'ready_to_publish' | 'publishing' | 'published' | 'unpublished';
  publishedAt?: string | null;
  legacySource?: string | null;
  legacyData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "takedown-requests".
 */
export interface TakedownRequest {
  id: number;
  requestId: string;
  requestType: 'takedown' | 'attribution' | 'source-correction' | 'license-correction';
  work?: (number | null) | Work;
  requester?: {
    name?: string | null;
    contact?: string | null;
    proof?: string | null;
  };
  status: 'received' | 'investigating' | 'approved' | 'rejected' | 'completed';
  decisionNote?: string | null;
  processedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publish-runs".
 */
export interface PublishRun {
  id: number;
  runId: string;
  trigger: 'manual' | 'scheduled' | 'ai';
  mode: 'preview' | 'publish' | 'rollback';
  status: 'queued' | 'in_progress' | 'succeeded' | 'failed' | 'cancelled';
  works?: (number | Work)[] | null;
  plannedChanges?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  step?: string | null;
  releasePath?: string | null;
  healthCheck?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  log?: string | null;
  error?: string | null;
  startedAt?: string | null;
  finishedAt?: string | null;
  actor?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-events".
 */
export interface AuditEvent {
  id: number;
  actorType: 'human' | 'ai' | 'system';
  actor?: (number | null) | User;
  action: string;
  targetType: string;
  targetId: string;
  before?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  after?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  requestId?: string | null;
  ip?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'characters';
        value: number | Character;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'submissions';
        value: number | Submission;
      } | null)
    | ({
        relationTo: 'works';
        value: number | Work;
      } | null)
    | ({
        relationTo: 'takedown-requests';
        value: number | TakedownRequest;
      } | null)
    | ({
        relationTo: 'publish-runs';
        value: number | PublishRun;
      } | null)
    | ({
        relationTo: 'audit-events';
        value: number | AuditEvent;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  displayName?: T;
  isServiceAccount?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  sha256?: T;
  mediaRole?: T;
  storageKind?: T;
  externalUrl?: T;
  sourcePath?: T;
  isAnimated?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "characters_select".
 */
export interface CharactersSelect<T extends boolean = true> {
  characterId?: T;
  name?: T;
  aliases?:
    | T
    | {
        value?: T;
        id?: T;
      };
  status?: T;
  inSubmissionForm?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  categoryId?: T;
  name?: T;
  description?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions_select".
 */
export interface SubmissionsSelect<T extends boolean = true> {
  title?: T;
  submissionId?: T;
  source?: T;
  sourceId?: T;
  sourceIds?:
    | T
    | {
        value?: T;
        id?: T;
      };
  asset?: T;
  sha256?: T;
  format?: T;
  mime?: T;
  bytes?: T;
  fields?:
    | T
    | {
        name?: T;
        characterText?: T;
        description?: T;
        tags?: T;
        originType?: T;
        originAuthor?: T;
        originUrl?: T;
        licenseType?: T;
        licenseNote?: T;
      };
  state?: T;
  review?: T;
  stateHistory?: T;
  submitter?:
    | T
    | {
        name?: T;
        github?: T;
      };
  origin?: T;
  humanDecision?:
    | T
    | {
        decision?: T;
        reason?: T;
        actor?: T;
        at?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works_select".
 */
export interface WorksSelect<T extends boolean = true> {
  workId?: T;
  slug?: T;
  name?: T;
  description?: T;
  commentary?: T;
  kind?: T;
  character?: T;
  categories?: T;
  tags?:
    | T
    | {
        value?: T;
        id?: T;
      };
  original?: T;
  preview?: T;
  large?: T;
  legacyPaths?:
    | T
    | {
        path?: T;
        thumbnailPath?: T;
        fullPath?: T;
        externalOriginalUrl?: T;
      };
  submitter?:
    | T
    | {
        name?: T;
        github?: T;
      };
  origin?: T;
  license?: T;
  status?: T;
  publishedAt?: T;
  legacySource?: T;
  legacyData?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "takedown-requests_select".
 */
export interface TakedownRequestsSelect<T extends boolean = true> {
  requestId?: T;
  requestType?: T;
  work?: T;
  requester?:
    | T
    | {
        name?: T;
        contact?: T;
        proof?: T;
      };
  status?: T;
  decisionNote?: T;
  processedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publish-runs_select".
 */
export interface PublishRunsSelect<T extends boolean = true> {
  runId?: T;
  trigger?: T;
  mode?: T;
  status?: T;
  works?: T;
  plannedChanges?: T;
  step?: T;
  releasePath?: T;
  healthCheck?: T;
  log?: T;
  error?: T;
  startedAt?: T;
  finishedAt?: T;
  actor?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-events_select".
 */
export interface AuditEventsSelect<T extends boolean = true> {
  actorType?: T;
  actor?: T;
  action?: T;
  targetType?: T;
  targetId?: T;
  before?: T;
  after?: T;
  requestId?: T;
  ip?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}