import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { resolveConfig } from './config.mjs';
import { createQueue } from './queue.mjs';
import { agentAction } from './agent.mjs';
import { fixtureI18n } from '../tools/localization/test-fixture.mjs';
const vocabulary = {ok:true,characterIds:new Set(['deepseek']),categoryIds:new Set(['meme'])};
const content = {name:'探头',description:'露出脑袋',commentary:'让我看看',characterId:'deepseek',categoryIds:['meme'],tags:['探头']};
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8DwHwAFAAH/q842iQAAAABJRU5ErkJggg==','base64');
test('Agent saves Chinese and each language; bad locale never loses prior content or marks manual',async t=>{
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'agent-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));
 const cfg=resolveConfig({storageRoot:path.join(root,'private')},{env:{}});const queue=await createQueue(cfg);
 const item=(await queue.enqueue({source:'web',sourceId:'web:agent',buffer:png,fields:{name:'probe'}})).item;
 const call=(action,input={})=>agentAction(queue,action,{id:item.id,...input},{vocabulary});
 const claimed=await call('claim');const auth={token:claimed.token};
 await assert.rejects(()=>call('claim'),/正在处理/);
 await assert.rejects(()=>call('draft',{...auth,content}),/读取/);
 await call('image',auth);
 const saved=await call('draft',{...auth,content,review:{verdict:'pass',confidence:.9,reason:'合规'}});
 await assert.rejects(()=>call('complete',auth),/i18n/);
 const locales=fixtureI18n(content.tags),sourceHash=saved.draft.i18n.sourceHash;
 await call('locale',{...auth,language:'en',sourceHash,content:locales.en});
 const bad=structuredClone(locales.ja);bad.tags=[];
 await assert.rejects(()=>call('locale',{...auth,language:'ja',sourceHash,content:bad}),/tags/);
 const stored=await queue.get(item.id);assert.equal(stored.state,'received');assert.equal(stored.agent.draft.name,content.name);assert.deepEqual(stored.agent.draft.i18n.en,locales.en);
 await call('locale',{...auth,language:'ja',sourceHash,content:locales.ja});
 assert.equal((await call('complete',auth)).result.verdict,'pass');
 await call('release',{...auth,reason:'technical issue'});assert.equal((await queue.get(item.id)).state,'received');
 await assert.rejects(()=>call('get',auth),/过期/);
});
