import { test } from 'node:test';
import assert from 'node:assert/strict';
import { publishedIssueGroups, reconcile, MARKER } from '../issue-reconcile.mjs';
const hash = 'a'.repeat(64);
const meta = [{ sha256: hash, status: 'published', source: 'github-issue', origin: { issue: 40, issueUrl: 'https://github.com/lmy414/ai-girl-stickers/issues/40', assetUrl: 'https://github.com/user-attachments/assets/abc-def' } }];
const works = [{ sha256: hash, id: `sticker_${hash.slice(0,24)}`, slug: 'deepseek202609270001', status: 'published' }];
const issue = { number: 40, state: 'open', labels: [{name:'sticker-submission'}], body: 'https://github.com/user-attachments/assets/abc-def' };
function fake() { const calls=[]; let comments=[]; let state='open'; const request=async(path, options={})=>{ calls.push({path, method:options.method||'GET', body:options.body}); if(path.endsWith('/comments') && options.method==='POST'){ comments.push({user:{login:'lmy414'},body:options.body.body}); return {}; } if(path.includes('/comments')) return comments; if(options.method==='PATCH'){ state='closed'; return {}; } return {...issue,state};}; return {calls,request}; }
test('只对实际发布的仓库 Issue 候选分组',()=>{ assert.equal(publishedIssueGroups(meta,works).size,1); assert.equal(publishedIssueGroups([{...meta[0],status:'ready'}],works).size,0); assert.equal(publishedIssueGroups(meta,[{...works[0],status:'draft'}]).size,0); });
test('留言先于关闭且重复执行不会再留言或关闭',async()=>{ const f=fake(); const first=await reconcile({meta,works,request:f.request,checkPage:async()=>true}); assert.equal(first.commented,1);assert.equal(first.closed,1);assert.ok(f.calls.find(c=>c.method==='POST').body.body.includes(MARKER));assert.ok(f.calls.findIndex(c=>c.method==='POST')<f.calls.findIndex(c=>c.method==='PATCH'));const second=await reconcile({meta,works,request:f.request,checkPage:async()=>true});assert.equal(second.commented,0);assert.equal(second.closed,0); });
test('已关闭但未留言仍补已收录提醒',async()=>{ const f=fake(); const request=async(path,opts)=>path.endsWith('/comments')&&opts?.method==='POST'?f.request(path,opts):path.includes('/comments')?[]:{...issue,state:'closed'}; const result=await reconcile({meta,works,request,checkPage:async()=>true});assert.equal(result.commented,1);assert.equal(result.closed,0); });
test('作品未上线或 Issue 新增未发布附件则不关闭',async()=>{ const f=fake(); let r=await reconcile({meta,works,request:f.request,checkPage:async()=>false,log:()=>{}});assert.equal(r.closed,0);assert.equal(r.commented,0);assert.equal(r.failed.length,1);const request=async(path,opts)=>path.includes('/comments')?[]:{...issue,body:issue.body+' https://github.com/user-attachments/assets/dead-beef'};r=await reconcile({meta,works,request,checkPage:async()=>true});assert.equal(r.skipped,1);assert.equal(r.closed,0); });
test('GitHub 留言失败保留 Issue 为 open 待重试',async()=>{const f=fake();const request=async(path,opts)=>opts?.method==='POST'?Promise.reject(new Error('rate limit')):f.request(path,opts);const r=await reconcile({meta,works,request,checkPage:async()=>true,log:()=>{}});assert.equal(r.closed,0);assert.equal(r.failed.length,1);assert.equal(f.calls.some(c=>c.method==='PATCH'),false);});
